# Tscan + ROI nose_upper
# Généré par scripts/generate_ubfc_dl_roi_configs.py
# Lancer : bash scripts/run_ubfc_dl_roi.sh Tscan nose_upper
BASE: ['']
TOOLBOX_MODE: "train_and_test"
TRAIN:
  BATCH_SIZE: 1
  EPOCHS: 5
  LR: 9e-3
  MODEL_FILE_NAME: UBFC_DL_Tscan_Nose_Upper
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False
    DATA_FORMAT: NDCHW
    DATA_PATH: "/media/simeon/rPPP-Data/Datasets/UBFC-rPPG/RawData"
    CACHED_PATH: "/media/simeon/rPPP-Data/Datasets/UBFC-rPPG/Preprocessed_DL"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized','Standardized']
      DATA_AUG: ['None']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False
    DATA_FORMAT: NDCHW
    DATA_PATH: "/media/simeon/rPPP-Data/Datasets/UBFC-rPPG/RawData"
    CACHED_PATH: "/media/simeon/rPPP-Data/Datasets/UBFC-rPPG/Preprocessed_DL"
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      DATA_AUG: ['None']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: True
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False
    DATA_FORMAT: NDCHW
    DATA_PATH: "/media/simeon/rPPP-Data/Datasets/UBFC-rPPG/RawData"
    CACHED_PATH: "/media/simeon/rPPP-Data/Datasets/UBFC-rPPG/Preprocessed_DL"
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp_ubfc_dl

MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10

INFERENCE:
  BATCH_SIZE: 1
  EVALUATION_METHOD: "FFT"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False
    WINDOW_SIZE: 10
  MODEL_PATH:   ""
